/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jnitest_JniUtils */

#ifndef _Included_com_test_jnitest_JniUtils
#define _Included_com_test_jnitest_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jnitest_JniUtils
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_jnitest_JniUtils_helloWorld
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_test_jnitest_JniUtils_staticCallHello
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
